contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.2.3
    packID: Expanse
    packName: Expanse (Deprecated)
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: Parses incident from Expanse in raw json to readable output
id: ExpanseParseRawIncident
inputs: []
name: Expanse Incident Playbook
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ba6bf399-1fb9-4f3c-89a0-d282a792edcd
      iscommand: false
      name: ""
      version: -1
    taskid: ba6bf399-1fb9-4f3c-89a0-d282a792edcd
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      expanse_raw_json_event:
        simple: ${incident.expanserawjsonevent}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Parses incident from Expanse in raw json to readable output
      id: 06f18e94-8923-4e60-85bc-0a3b6b818f3e
      iscommand: false
      name: Get Expanse Event
      script: ExpanseParseRawIncident
      type: regular
      version: -1
    taskid: 06f18e94-8923-4e60-85bc-0a3b6b818f3e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 270
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 315,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
