contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: e7b96e0d-7bbe-48c0-8135-c14c27580854
inputs: []
name: sharon - Just extract Indicators
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bd2d3506-b3e5-4756-87a2-eb0870ff638d
      iscommand: false
      name: ""
      version: -1
    taskid: bd2d3506-b3e5-4756-87a2-eb0870ff638d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      text:
        simple: ${incident}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Extract all indicators according to server indicators configuration
      id: 2ca963af-7f6a-4d19-86d8-719adc4be7d1
      iscommand: true
      name: extractIndicators
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: 2ca963af-7f6a-4d19-86d8-719adc4be7d1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
