contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    itemVersion: 2.0.10
    packID: Sixgill-Darkfeed
    packName: Sixgill Darkfeed - Annual Subscription
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: Set this playbook as an automated job in order to automatically download
  malware from new Darkfeed IOCs and run them through the "Darkfeed IOC detonation
  and proactive blocking" playbook
id: Darkfeed - malware download from feed
inputs:
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: sourceBrands:Sixgill_Darkfeed and sixgillfeedid:[darkfeed_010,darkfeed_002,darkfeed_012]
      and type:[URL,file]
    queryEntity: indicators
    results: null
    runFromLastJobTime: true
  required: false
  value: {}
name: Darkfeed - malware download from feed
outputs: []
quiet: true
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8913d0e7-b681-4f0e-81ac-f1c535c59a13
      iscommand: false
      name: ""
      version: -1
    taskid: 8913d0e7-b681-4f0e-81ac-f1c535c59a13
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    scriptarguments:
      File:
        complex:
          root: File
      Manual download:
        simple: "true"
      URL:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: URL.Data
              operator: notStartWith
              right:
                value:
                  simple: https://attack.mitre.org
          - - left:
                iscontext: true
                value:
                  simple: URL.Data
              operator: notStartWith
              right:
                value:
                  simple: https://virustotal.com
          - - left:
                iscontext: true
                value:
                  simple: URL.Data
              operator: notStartWith
              right:
                value:
                  simple: https://portal.cybersixgill.com
          root: URL
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 497d9ae3-f5d3-4f4a-8802-fc3a565c1975
      iscommand: false
      name: Darkfeed IOC detonation and proactive blocking
      playbookId: Darkfeed IOC detonation and proactive blocking
      type: playbook
      version: -1
    taskid: 497d9ae3-f5d3-4f4a-8802-fc3a565c1975
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 790
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: File.SHA1
      value:
        complex:
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: playbookQuery.type
              operator: isEqualString
              right:
                value:
                  simple: File
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.CustomFields.sha1
              operator: isNotEmpty
          root: playbookQuery
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the specified value exists in context. If the value exists,
        it will be set in context, otherwise no value will be set in context.
      id: df123ba9-a21a-412a-87f7-9748d813a962
      iscommand: false
      name: SHA-1
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: df123ba9-a21a-412a-87f7-9748d813a962
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: File.SHA256
      value:
        complex:
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: playbookQuery.type
              operator: isEqualString
              right:
                value:
                  simple: File
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.CustomFields.sha256
              operator: isNotEmpty
          root: playbookQuery
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the specified value exists in context. If the value exists,
        it will be set in context, otherwise no value will be set in context.
      id: de291ec9-4ad5-44bb-8459-483b5601a842
      iscommand: false
      name: SHA-256
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: de291ec9-4ad5-44bb-8459-483b5601a842
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 330
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: File.MD5
      value:
        complex:
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: playbookQuery.type
              operator: isEqualString
              right:
                value:
                  simple: File
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.CustomFields.md5
              operator: isNotEmpty
          root: playbookQuery
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the specified value exists in context. If the value exists,
        it will be set in context, otherwise no value will be set in context.
      id: f04b4607-0add-49fa-897b-19216e2e2a29
      iscommand: false
      name: MD5
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: f04b4607-0add-49fa-897b-19216e2e2a29
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 480
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: URL.Data
      value:
        complex:
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: playbookQuery.type
              operator: isEqualString
              right:
                value:
                  simple: URL
          root: playbookQuery
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the specified value exists in context. If the value exists,
        it will be set in context, otherwise no value will be set in context.
      id: e4808775-584c-45a1-8870-35c8a74240c8
      iscommand: false
      name: URL
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: e4808775-584c-45a1-8870-35c8a74240c8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 630
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 835,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
