contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.5.0
    itemVersion: 2.2.9
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: 'This playbook searches for a specific hash in the supported sandboxes.
  If the hash is known, the playbook provides a detailed analysis of the sandbox report.
  Currently supported sandboxes are Falcon X and Wildfire. '
id: Search For Hash In Sandbox - Generic
inputs:
- description: The SHA256 hash to search for.
  key: FileSha256
  playbookInputQuery: null
  required: false
  value: {}
name: Search For Hash In Sandbox - Generic
outputs:
- contextPath: AttackPattern
  description: The MITRE Attack pattern information.
  type: unknown
- contextPath: MITREATTACK
  description: Full MITRE data for the attack pattern.
  type: unknown
- contextPath: NonFoundHashes
  description: A list of hashes that are not found in the sandboxes.
  type: string
- contextPath: WildFire.Report
  description: The results of the Wildfire report.
  type: string
- contextPath: csfalconx.resource.sandbox
  description: The results of the Falcon X report.
  type: string
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 568ce337-1ee9-443e-8022-0fc40fff04aa
      iscommand: false
      name: ""
      version: -1
    taskid: 568ce337-1ee9-443e-8022-0fc40fff04aa
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 470,
          "y": -200
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "9"
      "yes":
      - "6"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: CrowdStrike Falcon X
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if the CrowdStrike Falcon X integration is available.
      id: ee043234-3d7b-4195-8ca7-1cbde477e677
      iscommand: false
      name: Is FalconX enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: ee043234-3d7b-4195-8ca7-1cbde477e677
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 230,
          "y": 150
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "9"
      "yes":
      - "5"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: WildFire-v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if the WildFire-v2 integration is available.
      id: dbdc45b0-9334-406c-8a0f-4d96d4b1c51b
      iscommand: false
      name: Is WildFire enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: dbdc45b0-9334-406c-8a0f-4d96d4b1c51b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 710,
          "y": 150
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      extended_data:
        simple: "true"
      format:
        simple: xml
      sha256:
        simple: ${inputs.FileSha256}
      verbose:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Searches for a specific hash in the WildFire sandbox.
      id: 17c289b8-e1d0-40ab-8880-5c64708b5225
      iscommand: true
      name: Search for hash in Wildfire
      script: '|||wildfire-report'
      type: regular
      version: -1
    taskid: 17c289b8-e1d0-40ab-8880-5c64708b5225
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 950,
          "y": 330
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      hashes:
        simple: ${inputs.FileSha256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Finds sandbox reports by providing an FQL filter and paging details.
      id: f1fa61ce-3ee3-4918-86af-e6d66a3c6b24
      iscommand: true
      name: Search for hash in FalconX
      script: '|||cs-fx-find-reports'
      type: regular
      version: -1
    taskid: f1fa61ce-3ee3-4918-86af-e6d66a3c6b24
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -40,
          "y": 320
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.FileSha256
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "1"
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ca8852d8-fa26-4061-8673-2e0f0710b967
      iscommand: false
      name: Is there a hash to check?
      type: condition
      version: -1
    taskid: ca8852d8-fa26-4061-8673-2e0f0710b967
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 470,
          "y": -40
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0eb7ea1e-8067-4c3c-8d44-9fa64f71e7ad
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 0eb7ea1e-8067-4c3c-8d44-9fa64f71e7ad
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 470,
          "y": 1340
        }
      }
  "13":
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: FalconX sandbox report
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      extended_data:
        simple: "true"
      ids:
        complex:
          accessor: reportIds
          root: csfalconx.resource.FindReport
          transformers:
          - operator: FirstArrayElement
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets a full report from the Falcon X sandbox.
      id: 0cc08ef9-5225-44a8-8221-553bb90807b1
      iscommand: true
      name: Get full report from FalconX
      script: '|||cs-fx-get-full-report'
      type: regular
      version: -1
    taskid: 0cc08ef9-5225-44a8-8221-553bb90807b1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -40,
          "y": 490
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: attack_id
                root: csfalconx.resource.sandbox.mitre_attacks
                transformers:
                - args:
                    item:
                      iscontext: true
                      value:
                        simple: csfalconx.resource.sandbox.mitre_attacks.parent.attack_id
                  operator: append
          operator: isNotEmpty
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 776cf8da-d5f6-4fcc-8c46-be9bda455b2e
      iscommand: false
      name: Are there MITRE findings?
      type: condition
      version: -1
    taskid: 776cf8da-d5f6-4fcc-8c46-be9bda455b2e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -40,
          "y": 1000
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      TechniqueID:
        simple: ${csfalconx.resource.sandbox.mitre_attacks.attack_id}
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: |-
        This playbook accepts as an input MITRE technique IDs.
        It provides the MITRE technique name and all the technique data using the MITRE integration.
        After extracting the MITRE data, the techniques are associated with the incident.
      id: 60bac145-90e5-4429-8609-c659c8c2a182
      iscommand: false
      name: Mitre Attack - Extract Technique Information From ID
      playbookId: Mitre Attack - Extract Technique Information From ID
      type: playbook
      version: -1
    taskid: 60bac145-90e5-4429-8609-c659c8c2a182
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -250,
          "y": 1170
        }
      }
  "19":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: WildFire.Report.Status
          operator: isNotEqualString
          right:
            value:
              simple: Success
      label: "no"
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "no":
      - "20"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: aad4cc28-d608-4319-8985-f4a20a3c9f87
      iscommand: false
      name: Were all hashes found?
      type: condition
      version: -1
    taskid: aad4cc28-d608-4319-8985-f4a20a3c9f87
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 950,
          "y": 1000
        }
      }
  "20":
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: NonFoundHashes
      value:
        complex:
          accessor: SHA256
          filters:
          - - left:
                iscontext: true
                value:
                  simple: WildFire.Report.Status
              operator: isNotEqualString
              right:
                value:
                  simple: Success
          root: WildFire.Report
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Set a value in context under the key you entered. If no value is entered, the script doesn't do anything.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: 87f2fab9-de14-4277-8357-8decd2d1b522
      iscommand: false
      name: Set non found hashes
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: 87f2fab9-de14-4277-8357-8decd2d1b522
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1220,
          "y": 1170
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: NonFoundHashes
      value:
        complex:
          accessor: sha256
          filters:
          - - left:
                iscontext: true
                value:
                  simple: csfalconx.resource.FindReport.reportIds
              operator: isEmpty
          root: csfalconx.resource.FindReport
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Set a value in context under the key you entered. If no value is entered, the script doesn't do anything.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: 5ac5a3af-906e-4065-81be-63d12e6ca8f3
      iscommand: false
      name: Set non found hashes
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: 5ac5a3af-906e-4065-81be-63d12e6ca8f3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -40,
          "y": 735
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      format:
        simple: pdf
      sha256:
        simple: ${inputs.FileSha256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets a PDF report of search results for hashes in the WildFire
        sandbox.
      id: f1e1594d-5b8b-4414-8efb-2682ee0bb1a2
      iscommand: true
      name: Get Wildfire PDF report
      script: '|||wildfire-report'
      type: regular
      version: -1
    taskid: f1e1594d-5b8b-4414-8efb-2682ee0bb1a2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 950,
          "y": 490
        }
      }
  "24":
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: Wildfire report
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      EntryID:
        complex:
          accessor: EntryID
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: InfoFile.Extension
              operator: isEqualString
              right:
                value:
                  simple: pdf
          root: InfoFile
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Converts a PDF file to an image file.
      id: 93e1ecdb-1db8-4189-8aea-f455c87ebab2
      iscommand: true
      name: Rasterize PDF
      script: '|||rasterize-pdf'
      type: regular
      version: -1
    taskid: 93e1ecdb-1db8-4189-8aea-f455c87ebab2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1190,
          "y": 830
        }
      }
  "25":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: InfoFile.Extension
          operator: isEqualString
          right:
            value:
              simple: pdf
      label: "yes"
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "19"
      "yes":
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 41001a52-b698-414c-8561-a9f8a3c2d620
      iscommand: false
      name: Is there a report to rasterize?
      type: condition
      version: -1
    taskid: 41001a52-b698-414c-8561-a9f8a3c2d620
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 950,
          "y": 650
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "16_9_#default#": 0.19,
      "19_9_#default#": 0.26,
      "1_9_no": 0.11,
      "3_9_no": 0.13,
      "7_9_#default#": 0.1
    },
    "paper": {
      "dimensions": {
        "height": 1605,
        "width": 1850,
        "x": -250,
        "y": -200
      }
    }
  }
