contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 344982ce-2225-4600-8527-e3dbd3650135
inputs:
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: type:Domain
    queryEntity: indicators
    results: null
    runFromLastJobTime: false
  required: false
  value: {}
name: TIM-Testing_dev
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7b363ddb-27ab-4502-83be-71c9f703009e
      iscommand: false
      name: ""
      version: -1
    taskid: 7b363ddb-27ab-4502-83be-71c9f703009e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Start Test?
      cc: null
      format: ""
      methods: []
      replyOptions:
      - "Yes"
      - "No"
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#default#':
      - "3"
      "Yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a11e7b9e-fd23-440e-8145-34c3f812bb7e
      iscommand: false
      name: Start testing?
      type: condition
      version: -1
    taskid: a11e7b9e-fd23-440e-8145-34c3f812bb7e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 2
    scriptarguments:
      extend-context:
        simple: domain_indicators_list
      text:
        simple: okblrsp.wmsistseg.com.br
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.extract.indicators
      id: 23d4a3fa-8763-4185-88f7-5ea13ceecd29
      iscommand: true
      name: Start testing - Get 5 domain indicators
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: 23d4a3fa-8763-4185-88f7-5ea13ceecd29
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 680,
          "y": 360
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ec7fd23f-ae1c-4f5f-852d-11733fa889e8
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: ec7fd23f-ae1c-4f5f-852d-11733fa889e8
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 710
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 2
    scriptarguments:
      CheckForWhoisDomainAgeCreation:
        simple: "True"
      CheckForWhoisRegistrant:
        simple: "True"
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: This playbook uses several sub playbooks to process and tag indicators
        based on the results of the Whois tool.
      id: 691bed2e-29ef-4e9c-835f-4361ebace363
      iscommand: false
      name: TIM - Process Domains With Whois
      playbookId: TIM - Process Domains With Whois
      type: playbook
      version: -1
    taskid: 691bed2e-29ef-4e9c-835f-4361ebace363
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 680,
          "y": 540
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 725,
        "width": 610,
        "x": 450,
        "y": 50
      }
    }
  }
