contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.2.0
    itemVersion: 2.2.9
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: "This playbook enables threat hunting for IOCs in your enterprise. It
  currently supports the following integrations: - Splunk\n- Qradar\n- Pan-os \n-
  Cortex data lake \n- Autofocus\n- Microsoft 365 Defender"
id: Threat Hunting - Generic
inputs:
- description: The MD5 hash file or an array of hashes to search.
  key: MD5
  playbookInputQuery: null
  required: false
  value: {}
- description: The SHA256 hash file or an array of hashes to search.
  key: SHA256
  playbookInputQuery: null
  required: false
  value: {}
- description: The hostname of the machine on which the file is located.
  key: Hostname
  playbookInputQuery: null
  required: false
  value: {}
- description: The SHA1 hash file or an array of hashes to search.
  key: SHA1
  playbookInputQuery: null
  required: false
  value: {}
- description: |
    The source or destination IP address to search. Can be a single address or an array of list of addresses.
  key: IPAddress
  playbookInputQuery: null
  required: false
  value: {}
- description: Domain or URL to search. Can be a single domain or URL or an array
    of domains or URLs to search. By default, the LIKE clause is used.
  key: URLDomain
  playbookInputQuery: null
  required: false
  value: {}
- description: 'A comma-separated list of internal IP ranges to check IP addresses
    against. The list should be provided in CIDR notation. An example of a list of
    ranges would be: "172.16.0.0/12,10.0.0.0/8,192.168.0.0/16" (without quotes). If
    a list is not provided, uses the default list provided in the IsIPInRanges script
    (the known IPv4 private address ranges).'
  key: InternalRange
  playbookInputQuery: null
  required: false
  value: {}
- description: The organization's internal domain name. This is provided for the script
    IsInternalHostName that checks if the detected hostnames are internal or external,
    if the hosts contain the internal domains suffix. For example, paloaltonetworks.com.
    If there is more than one domain, use the | character to separate values such
    as (paloaltonetworks.com|test.com).
  key: InternalDomainName
  playbookInputQuery: null
  required: false
  value: {}
- description: Provided for the script IsInternalHostName that checks if the detected
    host names are internal or external, if the hosts match the organization's naming
    convention. For example, the host testpc1 will have the following regex \w{6}\d{1}
  key: InternalHostRegex
  playbookInputQuery: null
  required: false
  value: {}
- description: The time frame to search in QRadar.
  key: QRadarTimeFrame
  playbookInputQuery: null
  required: false
  value:
    simple: LAST 7 DAYS
- description: The earliest time to search in Splunk.
  key: SplunkEarliestTime
  playbookInputQuery: null
  required: false
  value:
    simple: -7d@d
- description: The latest time to search in Splunk.
  key: SplunkLatestTime
  playbookInputQuery: null
  required: false
  value:
    simple: now
name: Threat Hunting - Generic
outputs:
- contextPath: Splunk.DetectedUsers
  description: Users detected based on the username field in your search.
  type: string
- contextPath: Splunk.DetectedInternalIPs
  description: Internal IP addresses detected by your search.
  type: string
- contextPath: Splunk.DetectedExternalIPs
  description: External IP addresses detected by your search.
  type: string
- contextPath: Splunk.DetectedInternalHosts
  description: Internal hostnames detected based on the fields in your search.
  type: string
- contextPath: Splunk.DetectedExternalHosts
  description: External hostnames detected based on the fields in your search.
  type: string
- contextPath: PANWHunting.DetectedUsers
  description: User or array of users that were detected during hunting.
  type: string
- contextPath: PANWHunting.DetectedInternalIPs
  description: Internal IP addresses detected based on fields and inputs in your search.
  type: string
- contextPath: PANWHunting.DetectedExternalIPs
  description: External IP addresses detected based on fields and inputs in your search.
  type: string
- contextPath: PANWHunting.DetectedInternalHosts
  description: Internal hostnames detected based on fields and inputs in your search.
  type: string
- contextPath: PANWHunting.DetectedExternalHosts
  description: External hostnames detected based on fields and inputs in your search.
  type: string
- contextPath: QRadar.DetectedUsers
  description: Users detected based on the username field in your search.
  type: string
- contextPath: QRadar.DetectedInternalIPs
  description: Internal IP addresses detected based on fields and inputs in your search.
  type: string
- contextPath: QRadar.DetectedExternalIPs
  description: External IP addresses detected based on fields and inputs in your search.
  type: string
- contextPath: QRadar.DetectedInternalHosts
  description: Internal host names detected based on hosts in your assets table. Note
    that the data accuracy depends on how the asset mapping is configured in QRadar.
  type: string
- contextPath: QRadar.DetectedExternalHosts
  description: External host names detected based on hosts in your assets table. Note
    that the data accuracy depends on how the asset mapping is configured in QRadar.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails
  description: Email objects containing relevant fields.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.InternetMessageId
  description: Internet Message ID of the email.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.SenderFromDomain
  description: Sender domain.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.EmailDirection
  description: Email direction (inbound/outbound).
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.DeliveryLocation
  description: Delivery location.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.AuthenticationDetails
  description: Authentication details (SPF, DKIM, DMARC, CompAuth)
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.DeliveryAction
  description: Email subject.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.AttachmentCount
  description: Number of attachments.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.ThreatNames
  description: Threat names.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.RecipientEmailAddress
  description: Recipient email address.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.EmailAction
  description: Email action.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.EmailLanguage
  description: Email language.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.SenderFromAddress
  description: Sender address.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.Timestamp
  description: Timestamp.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.SenderDisplayName
  description: Sender display name.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.SenderIPv4
  description: Sender IPv4.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.ConfidenceLevel
  description: Threat types.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.SHA256
  description: SHA256 of the attachments (if exist in the email).
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.Url
  description: URLs found in the email's body.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.UrlCount
  description: Number of URLs found in the email's body.
  type: string
- contextPath: Microsoft365Defender.RetrievedEmails.SenderIPv6
  description: Sender IPv6.
  type: string
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
      - "3"
      - "5"
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f7b21d57-eb4c-4233-8725-51010d27db08
      iscommand: false
      name: ""
      version: -1
    taskid: f7b21d57-eb4c-4233-8725-51010d27db08
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 230,
          "y": 60
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      IPAddress:
        simple: ${inputs.IPAddress}
      IndexName:
        simple: '*'
      InternalDomainName:
        simple: ${inputs.InternalDomainName}
      InternalHostRegex:
        simple: ${inputs.InternalHostRegex}
      InternalIPRange:
        simple: ${inputs.InternalRange}
      MD5:
        simple: ${inputs.MD5}
      SHA1:
        simple: ${inputs.SHA1}
      SHA256:
        simple: ${inputs.SHA256}
      SelectFields:
        simple: source,timestamp
      URLDomain:
        simple: ${inputs.URLDomain}
      earliest_time:
        complex:
          root: inputs.SplunkEarliestTime
      event_limit:
        simple: "100"
      latest_time:
        complex:
          root: inputs.SplunkLatestTime
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook queries Splunk for indicators such as file hashes,
        IP addresses, domains, or URLs. It returns detected users, IP addresses, and
        hostnames related to the indicators.
      id: faee0e93-b767-4148-8d8f-b1762d1e1039
      iscommand: false
      name: Splunk Indicator Hunting
      playbookName: Splunk Indicator Hunting
      type: playbook
      version: -1
    taskid: faee0e93-b767-4148-8d8f-b1762d1e1039
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 860,
          "y": 230
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      IPAddresses:
        simple: ${inputs.IPAddress}
      InternalDomainName:
        simple: ${inputs.InternalDomainName}
      InternalHostRegex:
        simple: ${inputs.InternalHostRegex}
      InternalRange:
        simple: ${inputs.InternalRange}
      MD5:
        simple: ${inputs.MD5}
      SHA1:
        simple: ${inputs.SHA1}
      SHA256:
        simple: ${inputs.SHA256}
      URLDomain:
        simple: ${inputs.URLDomain}
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: "This is a multipurpose playbook used for hunting and threat detection.
        The playbook receives inputs based on hashes, IP addresses, or domain names
        provided manually or from outputs from other playbooks. \nWith the received
        indicators, the playbook leverages data received by PANW products including
        Cortex Data Lake, Autofocus, and Pan-OS to search for IP addresses, host names
        and users related to the provided indicators.\nThe output provided by the
        playbook facilitates pivoting searches for possibly affected IP addresses
        or users."
      id: 41273c47-6b21-49dd-869a-35e115202d0a
      iscommand: false
      name: Palo Alto Networks - Hunting And Threat Detection
      playbookName: Palo Alto Networks - Hunting And Threat Detection
      type: playbook
      version: -1
    taskid: 41273c47-6b21-49dd-869a-35e115202d0a
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 20,
          "y": 230
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 68569c89-2090-4873-8dbc-aede46966200
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 68569c89-2090-4873-8dbc-aede46966200
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 230,
          "y": 440
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      IPAddress:
        simple: ${inputs.IPAddress}
      InternalRange:
        simple: ${inputs.InternalRange}
      InvestigationIPFields:
        simple: sourceip,destinationip
      InvestigationUserFields:
        simple: username
      MD5:
        simple: ${inputs.MD5}
      QradarIPfield:
        simple: sourceip,destinationip
      SHA1:
        simple: ${inputs.SHA1}
      SHA256:
        simple: ${inputs.SHA256}
      TimeFrame:
        complex:
          root: inputs.InternalHostRegex
      URLDomain:
        simple: ${inputs.URLDomain}
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: 'This playbook queries the QRadar SIEM for indicators such as file
        hashes, IP addresses, domains, or URLs. '
      id: 6f545ba4-aeb9-4c82-87d0-4e3a1f0b5826
      iscommand: false
      name: QRadar Indicator Hunting V2
      playbookName: QRadar Indicator Hunting V2
      type: playbook
      version: -1
    taskid: 6f545ba4-aeb9-4c82-87d0-4e3a1f0b5826
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 440,
          "y": 230
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      IPAddress:
        complex:
          root: inputs.IPAddress
      ResultsLimit:
        simple: "50"
      SHA256:
        complex:
          root: inputs.SHA256
      SearchTimeframe:
        simple: "7"
      Timeout:
        simple: "60"
      URLDomain:
        complex:
          root: inputs.URLDomain
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: fc0a94ba-5e88-4e2a-8a37-8bb33de4dda9
      iscommand: false
      name: Microsoft 365 Defender - Emails Indicators Hunt
      playbookName: Microsoft 365 Defender - Emails Indicators Hunt
      type: playbook
      version: -1
    taskid: fc0a94ba-5e88-4e2a-8a37-8bb33de4dda9
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -400,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 445,
        "width": 1640,
        "x": -400,
        "y": 60
      }
    }
  }
