contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 907a1db9-479a-4308-8e1b-791e2aeb6b44
inputs: []
name: zan_parent
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 561daef6-0eac-4cb4-87b4-a4262cd92269
      iscommand: false
      name: ""
      version: -1
    taskid: 561daef6-0eac-4cb4-87b4-a4262cd92269
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: sdsdsdssd
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: f1882ab9-c3aa-41d6-8e78-efcf7e9d4a45
      iscommand: false
      name: Untitled Task
      script: Print
      type: regular
      version: -1
    taskid: f1882ab9-c3aa-41d6-8e78-efcf7e9d4a45
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 60,
          "y": 200
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8fe84f88-361d-43d9-83b0-d5f49d1535e7
      iscommand: false
      name: Untitled Task
      type: title
      version: -1
    taskid: 8fe84f88-361d-43d9-83b0-d5f49d1535e7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 30,
          "y": 560
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 48d1876c-d254-4509-83a4-a6df47b8954a
      iscommand: false
      name: zan_child
      playbookId: 4507afae-5d3a-4eb6-8cd2-ed4f8bcebdd7
      type: playbook
      version: -1
    taskid: 48d1876c-d254-4509-83a4-a6df47b8954a
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 360
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 575,
        "width": 410,
        "x": 30,
        "y": 50
      }
    }
  }
