contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: ed797a00-841c-466e-8b52-55d7fdf1b36b
inputs: []
name: ThisIsPlaybookToInclude
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c3da56d9-d571-477e-8a9c-7ebc6087a01a
      iscommand: false
      name: ""
      version: -1
    taskid: c3da56d9-d571-477e-8a9c-7ebc6087a01a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0cd7c84d-eb55-4f61-8d69-d8dafad7755d
      iscommand: false
      name: this_is_automation_to_exclude
      script: 274af0d2-1568-4c1d-83fb-b34bbbae193d
      type: regular
      version: -1
    taskid: 0cd7c84d-eb55-4f61-8d69-d8dafad7755d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
