contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 1067f28d-9198-4869-8a84-0ba81297ac30
inputs: []
name: pb_55_66
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 14f20692-a335-4644-89e9-6b973703afad
      iscommand: false
      name: ""
      version: -1
    taskid: 14f20692-a335-4644-89e9-6b973703afad
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 780,
          "y": -60
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c4f976b1-511c-4d4d-8083-a7f36017f6ba
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: c4f976b1-511c-4d4d-8083-a7f36017f6ba
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 780,
          "y": 80
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9d62871b-6992-43d4-88a9-ea5d47b71de9
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 9d62871b-6992-43d4-88a9-ea5d47b71de9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 780,
          "y": 260
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 88909cf5-9487-4be8-89f7-8c85f83a33e8
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 88909cf5-9487-4be8-89f7-8c85f83a33e8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 780,
          "y": 410
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 565,
        "width": 380,
        "x": 780,
        "y": -60
      }
    }
  }
