contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.0.13
    packID: Code42
    packName: Code42
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: This playbook searches for files via Code42 security events by either
  MD5 or SHA256 hash. The data is output to the Code42.SecurityData context for use.
id: Code42 File Search
inputs:
- description: MD5 hash to search for
  key: MD5
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
      transformers:
      - operator: uniq
- description: SHA256 hash to search for
  key: SHA256
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
      transformers:
      - operator: uniq
name: Code42 File Search
outputs:
- contextPath: Code42.SecurityData
  description: Returned File Results
  type: unknown
- contextPath: Code42.SecurityData.EventTimestamp
  description: Timestamp for event
- contextPath: Code42.SecurityData.FileCreated
  description: File creation date
- contextPath: Code42.SecurityData.EndpointID
  description: Code42 device ID
- contextPath: Code42.SecurityData.DeviceUsername
  description: Username that device is associated with in Code42
- contextPath: Code42.SecurityData.EmailFrom
  description: Sender email address for email exfiltration events
- contextPath: Code42.SecurityData.EmailTo
  description: Recipient email address for email exfiltration events
- contextPath: Code42.SecurityData.EmailSubject
  description: Email subject line for email exfiltration events
- contextPath: Code42.SecurityData.EventID
  description: Security Data event ID
- contextPath: Code42.SecurityData.EventType
  description: Type of Security Data event
- contextPath: Code42.SecurityData.FileCategory
  description: Type of file as determined by Code42 engine
- contextPath: Code42.SecurityData.FileOwner
  description: Owner of file
- contextPath: Code42.SecurityData.FileName
  description: File name
- contextPath: Code42.SecurityData.FilePath
  description: Path to file
- contextPath: Code42.SecurityData.FileSize
  description: Size of file in bytes
- contextPath: Code42.SecurityData.FileModified
  description: File modification date
- contextPath: Code42.SecurityData.FileMD5
  description: MD5 hash of file
- contextPath: Code42.SecurityData.FileHostname
  description: Hostname where file event was captured
- contextPath: Code42.SecurityData.DevicePrivateIPAddress
  description: Private IP addresses of device where event was captured
- contextPath: Code42.SecurityData.DevicePublicIPAddress
  description: Public IP address of device where event was captured
- contextPath: Code42.SecurityData.RemovableMediaType
  description: Type of removable media
- contextPath: Code42.SecurityData.RemovableMediaCapacity
  description: Total capacity of removable media in bytes
- contextPath: Code42.SecurityData.RemovableMediaMediaName
  description: Full name of removable media
- contextPath: Code42.SecurityData.RemovableMediaName
  description: Name of removable media
- contextPath: Code42.SecurityData.RemovableMediaSerialNumber
  description: Serial number for removable medial device
- contextPath: Code42.SecurityData.RemovableMediaVendor
  description: Vendor name for removable device
- contextPath: Code42.SecurityData.FileSHA256
  description: SHA256 hash of file
- contextPath: Code42.SecurityData.FileShared
  description: Whether file is shared using cloud file service
- contextPath: Code42.SecurityData.FileSharedWith
  description: Accounts that file is shared with on cloud file service
- contextPath: Code42.SecurityData.Source
  description: Source of file event, Cloud or Endpoint
- contextPath: Code42.SecurityData.ApplicationTabURL
  description: URL associated with application read event
- contextPath: Code42.SecurityData.ProcessName
  description: Process name for application read event
- contextPath: Code42.SecurityData.ProcessOwner
  description: Process owner for application read event
- contextPath: Code42.SecurityData.WindowTitle
  description: Process name for application read event
- contextPath: Code42.SecurityData.FileURL
  description: URL of file on cloud file service
- contextPath: Code42.SecurityData.Exposure
  description: Exposure type for event
- contextPath: Code42.SecurityData.SharingTypeAdded
  description: Type of sharing added to file
- contextPath: File
  description: The file object.
  type: unknown
- contextPath: File.Name
  description: File name
- contextPath: File.Path
  description: File path
- contextPath: File.Size
  description: File size in bytes
- contextPath: File.MD5
  description: MD5 hash of file
- contextPath: File.SHA256
  description: SHA256 hash of file
- contextPath: File.Hostname
  description: Hostname where file event was captured
sourceplaybookid: Code42 File Search
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d045a003-2e7f-4f47-80c7-3882baf399b6
      iscommand: false
      name: ""
      version: -1
    taskid: d045a003-2e7f-4f47-80c7-3882baf399b6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 280,
          "y": -140
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Code42
                - - left:
                      iscontext: true
                      value:
                        simple: state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "2"
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 746c1a4e-7084-45f1-86e6-e9764ffbbf5c
      iscommand: false
      name: Is Code42 Integration Active?
      type: condition
      version: -1
    taskid: 746c1a4e-7084-45f1-86e6-e9764ffbbf5c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 280,
          "y": 160
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.SHA256
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 935cb1d6-e328-4a8e-888f-347c3b33ce11
      iscommand: false
      name: Does SHA256 Exist?
      type: condition
      version: -1
    taskid: 935cb1d6-e328-4a8e-888f-347c3b33ce11
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 20,
          "y": 370
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.MD5
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1d0dfb1f-6874-41e9-8593-fca2a96c58c4
      iscommand: false
      name: Does MD5 Exist?
      type: condition
      version: -1
    taskid: 1d0dfb1f-6874-41e9-8593-fca2a96c58c4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 532.5,
          "y": 370
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      hash:
        simple: ${inputs.SHA256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e03a5e72-1695-4322-8072-22f076aeceed
      iscommand: true
      name: Code42 Search by SHA256
      script: '|||code42-securitydata-search'
      type: regular
      version: -1
    taskid: e03a5e72-1695-4322-8072-22f076aeceed
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 20,
          "y": 630
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      hash:
        simple: ${inputs.MD5}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9eda738e-0108-4e18-8d30-d3a20089c0a6
      iscommand: true
      name: Code42 Search by MD5
      script: '|||code42-securitydata-search'
      type: regular
      version: -1
    taskid: 9eda738e-0108-4e18-8d30-d3a20089c0a6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 532.5,
          "y": 630
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7f03d6ab-3bb8-4bd5-867b-fe853fa38684
      iscommand: false
      name: Complete
      type: title
      version: -1
    taskid: 7f03d6ab-3bb8-4bd5-867b-fe853fa38684
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 280,
          "y": 1040
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1245,
        "width": 892.5,
        "x": 20,
        "y": -140
      }
    }
  }
