contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 907a1db9-479a-4308-8e1b-791e2aeb6b44
inputs: []
name: zan_parent
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a676eed4-8310-4868-8800-593704d64aac
      iscommand: false
      name: ""
      version: -1
    taskid: a676eed4-8310-4868-8800-593704d64aac
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: sdsdsdssd
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: a8f782dd-6715-48dc-808f-ef8e12d3667d
      iscommand: false
      name: Untitled Task
      script: Print
      type: regular
      version: -1
    taskid: a8f782dd-6715-48dc-808f-ef8e12d3667d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 60,
          "y": 200
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 38b53547-1a72-4348-8e24-c72109df8e37
      iscommand: false
      name: Untitled Task
      type: title
      version: -1
    taskid: 38b53547-1a72-4348-8e24-c72109df8e37
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 30,
          "y": 560
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 5e6e51a3-9164-475b-8016-299720e4a70f
      iscommand: false
      name: zan_child
      playbookId: 4507afae-5d3a-4eb6-8cd2-ed4f8bcebdd7
      type: playbook
      version: -1
    taskid: 5e6e51a3-9164-475b-8016-299720e4a70f
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 360
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 575,
        "width": 410,
        "x": 30,
        "y": 50
      }
    }
  }
