contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: c75141cb-3a40-4a00-8d3a-eff9b5d8e88d
inputs: []
name: Outer Loop
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cf9f7529-e46c-4a5e-8f31-1b4f16acf33e
      iscommand: false
      name: ""
      version: -1
    taskid: cf9f7529-e46c-4a5e-8f31-1b4f16acf33e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      builtincondition:
      - - left:
            iscontext: true
            value:
              simple: counter
          operator: isEqualString
          right:
            value:
              simple: "9"
      exitCondition: ""
      iscommand: false
      max: 10000
      wait: 200
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4bd07aa9-fef0-45e2-836f-4c2103ca08f8
      iscommand: false
      name: Inner Loop
      playbookId: dec60c8a-04f0-4e91-8206-88dcd94ed5fe
      type: playbook
      version: -1
    taskid: 4bd07aa9-fef0-45e2-836f-4c2103ca08f8
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 350
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9a51fab4-9beb-4001-8c66-21d490c2c925
      iscommand: false
      name: Done. Proceed?
      type: regular
      version: -1
    taskid: 9a51fab4-9beb-4001-8c66-21d490c2c925
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 520
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: counter
      value:
        simple: "0"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 67ddc5e6-18df-44da-82f3-16610ea0932f
      iscommand: false
      name: Set counter
      script: Set
      type: regular
      version: -1
    taskid: 67ddc5e6-18df-44da-82f3-16610ea0932f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 180
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 565,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
