contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 344982ce-2225-4600-8527-e3dbd3650135
inputs: []
name: TIM-Testing_dev
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7b363ddb-27ab-4502-83be-71c9f703009e
      iscommand: false
      name: ""
      version: -1
    taskid: 7b363ddb-27ab-4502-83be-71c9f703009e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Start Test?
      cc: null
      format: ""
      methods: []
      replyOptions:
      - "Yes"
      - "No"
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#default#':
      - "3"
      "Yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a11e7b9e-fd23-440e-8145-34c3f812bb7e
      iscommand: false
      name: Start testing?
      type: condition
      version: -1
    taskid: a11e7b9e-fd23-440e-8145-34c3f812bb7e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 2
    scriptarguments:
      extend-context:
        simple: domain_indicators_list
      limit:
        simple: "5"
      query:
        simple: type:domain
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets a list of indicator objects and the associated indicator outputs
        that match the specified query and filters. The results are returned in a
        structured data file.
      id: 02940705-d8b9-4914-8218-2898e6f401d9
      iscommand: false
      name: Start testing - Get 5 domain indicators
      script: GetIndicatorsByQuery
      type: regular
      version: -1
    taskid: 02940705-d8b9-4914-8218-2898e6f401d9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 680,
          "y": 360
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 93451d30-6ed2-4515-87fc-be76099e9df0
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 93451d30-6ed2-4515-87fc-be76099e9df0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 710
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 2199560e-14d0-4529-8120-2e5cf94db5db
      iscommand: false
      name: TIM - Process Domains With Whois
      playbookId: TIM - Process Domains With Whois
      type: playbook
      version: -1
    taskid: 2199560e-14d0-4529-8120-2e5cf94db5db
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 680,
          "y": 540
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 725,
        "width": 610,
        "x": 450,
        "y": 50
      }
    }
  }
