contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 344982ce-2225-4600-8527-e3dbd3650135
inputs:
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: 'type:Domain '
    queryEntity: indicators
    results: null
    runFromLastJobTime: false
  required: false
  value: {}
name: TIM-Testing_dev
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7b363ddb-27ab-4502-83be-71c9f703009e
      iscommand: false
      name: ""
      version: -1
    taskid: 7b363ddb-27ab-4502-83be-71c9f703009e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Start Test?
      cc: null
      format: ""
      methods: []
      replyOptions:
      - "Yes"
      - "No"
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#default#':
      - "3"
      "Yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a11e7b9e-fd23-440e-8145-34c3f812bb7e
      iscommand: false
      name: Start testing?
      type: condition
      version: -1
    taskid: a11e7b9e-fd23-440e-8145-34c3f812bb7e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: domain_indicators_list
      limit:
        simple: "5"
      query:
        simple: type:domain
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets a list of indicator objects and the associated indicator outputs
        that match the specified query and filters. The results are returned in a
        structured data file.
      id: 7de45912-6258-48a2-8064-7f09155b1130
      iscommand: false
      name: Start testing - Get 5 domain indicators
      script: GetIndicatorsByQuery
      type: regular
      version: -1
    taskid: 7de45912-6258-48a2-8064-7f09155b1130
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e04533ed-9986-4b3d-8bdf-8119b8107611
      iscommand: false
      name: Abort testing
      type: title
      version: -1
    taskid: e04533ed-9986-4b3d-8bdf-8119b8107611
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1140
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 76946d07-33df-4a2b-8e13-a103dcd9599e
      iscommand: false
      name: TIM - Process Domain Age With Whois
      playbookId: TIM - Process Domain Age With Whois
      type: playbook
      version: -1
    taskid: 76946d07-33df-4a2b-8e13-a103dcd9599e
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -30,
          "y": 870
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 4d2f4c1b-4065-467e-8178-973cba9ee3e6
      iscommand: false
      name: TIM - Process Domain Registrant With Whois
      playbookId: TIM - Process Domain Registrant With Whois
      type: playbook
      version: -1
    taskid: 4d2f4c1b-4065-467e-8178-973cba9ee3e6
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -30,
          "y": 1030
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 2199560e-14d0-4529-8120-2e5cf94db5db
      iscommand: false
      name: TIM - Process Domains With Whois
      playbookId: TIM - Process Domains With Whois
      type: playbook
      version: -1
    taskid: 2199560e-14d0-4529-8120-2e5cf94db5db
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -30,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1155,
        "width": 860,
        "x": -30,
        "y": 50
      }
    }
  }
