contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    itemVersion: 2.1.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: |-
  This playbook isolates a given endpoint via various endpoint product integrations.
  Make sure to provide the valid playbook input for the integration you are using.
id: Isolate Endpoint - Generic V2
inputs:
- description: The hostname of the endpoint to isolate.
  key: Endpoint_hostname
  playbookInputQuery: null
  required: false
  value: {}
- description: Hosts that were detected as infected during the manual hunting.
  key: ManualHunting.DetectedHosts
  playbookInputQuery: null
  required: false
  value: {}
- description: The IP of the endpoint to isolate.
  key: Endpoint_ip
  playbookInputQuery: null
  required: false
  value: {}
- description: The ID of the endpoint to isolate.
  key: Endpoint_id
  playbookInputQuery: null
  required: false
  value: {}
name: Isolate Endpoint - Generic V2
outputs:
- contextPath: CbResponse.Sensors.CbSensorID
  description: Carbon Black Response Sensors ids that has been isolated.
  type: string
- contextPath: Endpoint
  description: The isolated enpoint.
  type: string
- contextPath: Traps.Isolate.EndpointID
  description: The ID of the endpoint.
  type: string
- contextPath: Traps.IsolateResult.Status
  description: The status of the isolation operation.
  type: string
- contextPath: Cybereason.Machine
  description: Cybereason machine name.
- contextPath: Cybereason.IsIsolated
  description: Whether the machine is isolated.
- contextPath: Endpoint.Hostname
  description: Hostname of the endpoint.
- contextPath: PaloAltoNetworksXDR.Endpoint.endpoint_id
  description: The endpoint ID.
- contextPath: PaloAltoNetworksXDR.Endpoint.endpoint_name
  description: The endpoint name.
- contextPath: PaloAltoNetworksXDR.Endpoint.endpoint_status
  description: The status of the endpoint.
- contextPath: PaloAltoNetworksXDR.Endpoint.ip
  description: The endpoint's IP address.
- contextPath: PaloAltoNetworksXDR.Endpoint.is_isolated
  description: Whether the endpoint is isolated.
- contextPath: CbResponse.Sensors.Status
  description: Sensor status.
  type: unknown
- contextPath: CbResponse.Sensors.Isolated
  description: Whether the sensor is isolated.
  type: unknown
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
      - "7"
      - "9"
      - "10"
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 20f01f93-7b37-4f3f-8c17-a466dac351ef
      iscommand: false
      name: ""
      version: -1
    taskid: 20f01f93-7b37-4f3f-8c17-a466dac351ef
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 910,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 050d36dd-0ec3-4490-827e-e210ac5e9a04
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 050d36dd-0ec3-4490-827e-e210ac5e9a04
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      Hostname:
        simple: ${inputs.Endpoint_hostname}
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook isolates an endpoint based on the hostname provided.
      id: 31a268a0-3862-4dcb-8549-b55d0ad936a0
      iscommand: false
      name: Isolate Endpoint - Cybereason
      playbookName: Isolate Endpoint - Cybereason
      type: playbook
      version: -1
    taskid: 31a268a0-3862-4dcb-8549-b55d0ad936a0
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      endpoint_id:
        simple: ${inputs.Endpoint_id}
      hostname:
        simple: ${inputs.Endpoint_hostname}
      ip_list:
        simple: ${inputs.Endpoint_ip}
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook accepts an XDR endpoint ID and isolates it using
        the 'Palo Alto Networks Cortex XDR - Investigation and Response' integration.
      id: 46562ad2-14ed-4064-8ce8-9adfb791d660
      iscommand: false
      name: Cortex XDR - Isolate Endpoint
      playbookName: Cortex XDR - Isolate Endpoint
      type: playbook
      version: -1
    taskid: 46562ad2-14ed-4064-8ce8-9adfb791d660
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      Device_id:
        simple: ${inputs.Endpoint_id}
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook will auto isolate endpoints by the device ID that
        was provided in the playbook.
      id: 2604374d-9538-4451-8064-2f5bb5c6dd81
      iscommand: false
      name: Crowdstrike Falcon - Isolate Endpoint
      playbookName: Crowdstrike Falcon - Isolate Endpoint
      type: playbook
      version: -1
    taskid: 2604374d-9538-4451-8064-2f5bb5c6dd81
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 195
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      Endpoint_id:
        simple: ${inputs.Endpoint_id}
      Hostname:
        simple: ${inputs.Endpoint_hostname}
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook will auto isolate endpoints by the endpoint ID that
        was provided in the playbook.
      id: 48226108-0787-44b0-80f6-cf333758b5e8
      iscommand: false
      name: FireEye HX - Isolate Endpoint
      playbookName: FireEye HX - Isolate Endpoint
      type: playbook
      version: -1
    taskid: 48226108-0787-44b0-80f6-cf333758b5e8
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 195
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      Hostname:
        simple: ${inputs.Endpoint_hostname}
      Sensor_id:
        simple: ${inputs.Endpoint_id}
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Carbon Black Response - isolate an endpoint for a given hostname.
      id: 04a17761-3b84-492f-87c6-ef29fc4adc7d
      iscommand: false
      name: Block Endpoint - Carbon Black Response V2
      playbookName: Block Endpoint - Carbon Black Response V2
      type: playbook
      version: -1
    taskid: 04a17761-3b84-492f-87c6-ef29fc4adc7d
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 2100,
        "x": 50,
        "y": 50
      }
    }
  }
