contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: d53d1c5f-d129-4689-8af6-890970a3df32
inputs: []
name: pb-1
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6e964dce-813b-4efa-834e-b7032a82745d
      iscommand: false
      name: ""
      version: -1
    taskid: 6e964dce-813b-4efa-834e-b7032a82745d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 710,
          "y": 20
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2b7959e3-a07b-4e6c-824c-be585832b117
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 2b7959e3-a07b-4e6c-824c-be585832b117
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 710,
          "y": 160
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 235,
        "width": 380,
        "x": 710,
        "y": 20
      }
    }
  }
