contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: f6af2e53-80d3-4d41-811b-d622a9e2ee6e
inputs:
- description: ""
  key: Sleeptime
  playbookInputQuery: null
  required: false
  value:
    simple: "5"
name: zan - inner loop
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9d513e29-9391-4455-8a15-d43d1c2ad748
      iscommand: false
      name: ""
      version: -1
    taskid: 9d513e29-9391-4455-8a15-d43d1c2ad748
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    reputationcalc: 2
    scriptarguments:
      value:
        simple: Entered loop 8.8.8.8
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 2f0a8453-4b06-430b-8ce6-f2c5cc8acd48
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 2f0a8453-4b06-430b-8ce6-f2c5cc8acd48
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: ${inputs.Sleeptime}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: 4437501d-1b92-4bf7-8e3c-4cb018b52192
      iscommand: false
      name: Sleep
      script: Sleep
      type: regular
      version: -1
    taskid: 4437501d-1b92-4bf7-8e3c-4cb018b52192
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    reputationcalc: 2
    scriptarguments:
      value:
        simple: Exiting loop
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 6d5d17b7-d9c5-483b-8fda-6d3cb9d35cc6
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 6d5d17b7-d9c5-483b-8fda-6d3cb9d35cc6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 590
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 635,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
