contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 81906b4b-bb11-4397-8a3a-268094e30b9b
inputs:
- description: ""
  key: ""
  playbookInputQuery: null
  required: false
  value: {}
name: test22_23
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c2dc5e6c-cb67-4cdb-8cee-b6c5045e941d
      iscommand: false
      name: ""
      version: -1
    taskid: c2dc5e6c-cb67-4cdb-8cee-b6c5045e941d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f579d6e3-ba4f-4d5f-8489-2d66e6e0ae4d
      iscommand: false
      name: foo script
      script: c6146778-5598-4168-8d06-896c3c945ad8
      type: regular
      version: -1
    taskid: f579d6e3-ba4f-4d5f-8489-2d66e6e0ae4d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 980,
          "y": 350
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      arg1:
        simple: "23324"
      arg2:
        simple: ere
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        First create new instance of "HelloWorld Feed (Community Contribution)"
      id: 4001e438-be11-4aa2-8791-95e72db6479e
      iscommand: false
      name: zan_script1
      script: 40f52bf9-bc24-42fe-8ccf-914336cde3b9
      type: regular
      version: -1
    taskid: 4001e438-be11-4aa2-8791-95e72db6479e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 160,
          "y": 330
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "1"
      "yes":
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      left:
        simple: "12"
      right:
        simple: "34"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: e25dce50-6433-47f9-8c33-5eef9f26e974
      iscommand: false
      name: arevalue
      script: AreValuesEqual
      type: condition
      version: -1
    taskid: e25dce50-6433-47f9-8c33-5eef9f26e974
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 160
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: eafcde42-4f62-4d19-87d3-7dd1512daf81
      iscommand: false
      name: Untitled Task
      type: title
      version: -1
    taskid: eafcde42-4f62-4d19-87d3-7dd1512daf81
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 890
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 905,
        "width": 1200,
        "x": 160,
        "y": 50
      }
    }
  }
