contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: ea23a0bc-7701-472c-82b0-dd2896c411d3
inputs: []
name: sharon's playbook matryoshka - large
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3a74c4fe-4f26-4dcf-8bcd-901ef6fad8a5
      iscommand: false
      name: ""
      version: -1
    taskid: 3a74c4fe-4f26-4dcf-8bcd-901ef6fad8a5
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      endpoint_name:
        simple: cyradis-10
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: b2fd6e64-81ff-4707-8a41-c26c61a41348
      iscommand: false
      name: sharon's playbook matryoshka - medium
      playbookId: 29eee818-6c5d-4466-8b15-db565cd6fd67
      type: playbook
      version: -1
    taskid: b2fd6e64-81ff-4707-8a41-c26c61a41348
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 300
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      listData:
        simple: large
      listName:
        simple: ${list_name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Add data to a list
      id: 49581a2f-9331-4a80-8b3b-09eaad7430f4
      iscommand: true
      name: addToList
      script: Builtin|||addToList
      type: regular
      version: -1
    taskid: 49581a2f-9331-4a80-8b3b-09eaad7430f4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 480
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      listName:
        simple: ${list_name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Get a list from lists repository
      id: d732d2de-52e8-464c-8185-40aa676ce0ea
      iscommand: true
      name: getList
      script: Builtin|||getList
      type: regular
      version: -1
    taskid: d732d2de-52e8-464c-8185-40aa676ce0ea
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 660
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 705,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
