contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.0.12
    packID: illuminate
    packName: Analyst1
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: A quick demonstration of the various Analyst1 enrichment commands.
id: Analyst1 Integration Demonstration
inputs: []
name: Analyst1 Integration Demonstration
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8b0bdd64-91d3-4b4c-8ef4-355d7ec2fb3e
      iscommand: false
      name: ""
      version: -1
    taskid: 8b0bdd64-91d3-4b4c-8ef4-355d7ec2fb3e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: IndicatorType=indicator_type
      value:
        simple: ${incident.details}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 11464b2f-f56f-426f-859d-a58a963eee92
      iscommand: false
      name: Parse Incident Details
      script: ParseJSON
      type: regular
      version: -1
    taskid: 11464b2f-f56f-426f-859d-a58a963eee92
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 195
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: Domain
      label: domain
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: Email
      label: email
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: URL
      label: url
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: inList
          right:
            value:
              simple: File MD5,File SHA-1,File SHA-256
      label: file
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: HTTP Request
      label: HTTP Request
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: IP
      - - left:
            iscontext: true
            value:
              simple: ${incident.labels.Indicator}
          operator: containsGeneral
          right:
            value:
              simple: .
      label: IPV4
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: IP
      - - left:
            iscontext: true
            value:
              simple: ${incident.labels.Indicator}
          operator: containsGeneral
          right:
            value:
              simple: ':'
      label: IPV6
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: File
      label: MUTEX
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: String
      label: String
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      HTTP Request:
      - "7"
      IPV4:
      - "12"
      IPV6:
      - "9"
      MUTEX:
      - "10"
      String:
      - "11"
      domain:
      - "3"
      email:
      - "4"
      file:
      - "6"
      url:
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 600de374-b058-4f8f-8a22-3809b34e4c67
      iscommand: false
      name: Determine Indicator Type
      type: condition
      version: -1
    taskid: 600de374-b058-4f8f-8a22-3809b34e4c67
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Analyst1
      id: d433f330-a2ff-49af-8828-5eca11a05aad
      iscommand: true
      name: Enrich Domain with Analyst1 Data
      script: Analyst1|||domain
      type: regular
      version: -1
    taskid: d433f330-a2ff-49af-8828-5eca11a05aad
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -10,
          "y": 475
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      email:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Analyst1
      id: 3f2838b5-6b4f-4bd3-8dd0-a385d9cf7fa6
      iscommand: true
      name: Enrich Email with Analyst1 Data
      script: Analyst1|||email
      type: regular
      version: -1
    taskid: 3f2838b5-6b4f-4bd3-8dd0-a385d9cf7fa6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 3060,
          "y": 520
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      url:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Analyst1
      id: cfe6df5f-b8d3-43e6-889d-71c16cbf4642
      iscommand: true
      name: Enrich URL with Analyst1 Data
      script: Analyst1|||url
      type: regular
      version: -1
    taskid: cfe6df5f-b8d3-43e6-889d-71c16cbf4642
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 570
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      file:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Analyst1
      id: 3f35ab7a-acaa-46f8-8df9-573c3313939e
      iscommand: true
      name: Enrich File with Analyst1 Data
      script: Analyst1|||file
      type: regular
      version: -1
    taskid: 3f35ab7a-acaa-46f8-8df9-573c3313939e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 2630,
          "y": 545
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      http-request:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Analyst1
      id: 1a12da4c-3f89-44a4-8d96-3be99d35ece8
      iscommand: true
      name: Enrich HTTP Request with Analyst1 Data
      script: Analyst1|||analyst1-enrich-http-request
      type: regular
      version: -1
    taskid: 1a12da4c-3f89-44a4-8d96-3be99d35ece8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 2200,
          "y": 570
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a2db7be6-9451-45c8-8ae7-231fbe9a6731
      iscommand: true
      name: Enrich IPV6 with Analyst1 Data
      script: '|||analyst1-enrich-ipv6'
      type: regular
      version: -1
    taskid: a2db7be6-9451-45c8-8ae7-231fbe9a6731
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      mutex:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Analyst1
      id: f02c6099-e632-43b1-8c88-d440913865df
      iscommand: true
      name: Enrich MUTEX with Analyst1 Data
      script: Analyst1|||analyst1-enrich-mutex
      type: regular
      version: -1
    taskid: f02c6099-e632-43b1-8c88-d440913865df
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 3480,
          "y": 465
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      string:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Analyst1
      id: d21e8959-8785-420f-8d60-f5d0a34af8ff
      iscommand: true
      name: Enrich String with Analyst1 Data
      script: Analyst1|||analyst1-enrich-string
      type: regular
      version: -1
    taskid: d21e8959-8785-420f-8d60-f5d0a34af8ff
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1780,
          "y": 615
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Analyst1
      id: bc79e3f9-b069-49f8-84f1-114701110bfd
      iscommand: true
      name: Enrich IPV4 with Analyst1 Data
      script: Analyst1|||ip
      type: regular
      version: -1
    taskid: bc79e3f9-b069-49f8-84f1-114701110bfd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 520
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 660,
        "width": 3870,
        "x": -10,
        "y": 50
      }
    }
  }
