contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    itemVersion: 1.7.4
    packID: CrowdStrikeFalcon
    packName: CrowdStrike Falcon
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: This playbook will auto isolate endpoints by the device ID that was provided
  in the playbook.
id: Crowdstrike Falcon - Isolate Endpoint
inputs:
- description: The device ID to isolate.
  key: Device_id
  playbookInputQuery: null
  required: false
  value: {}
name: Crowdstrike Falcon - Isolate Endpoint
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 196d9fe6-0849-4949-80f4-b5fae30a5602
      iscommand: false
      name: ""
      version: -1
    taskid: 196d9fe6-0849-4949-80f4-b5fae30a5602
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 40
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "2"
      "yes":
      - "3"
    note: false
    quietmode: 0
    results:
    - brandInstances
    scriptarguments:
      brandname:
        simple: CrowdstrikeFalcon
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if the integration brand is available. Otherwise
        returns 'no'.
      id: 2fc5acfc-b289-46c6-8ba5-d7c3f1c82f47
      iscommand: false
      name: Is Crowdstrike Falcon  enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 2fc5acfc-b289-46c6-8ba5-d7c3f1c82f47
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2d65723d-5bc8-4982-818d-eef2ffcb40c0
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 2d65723d-5bc8-4982-818d-eef2ffcb40c0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1760
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Device_id
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: abc1a40e-2ae6-4928-8530-f9baf3ce7760
      iscommand: false
      name: Is there Device ID?
      type: condition
      version: -1
    taskid: abc1a40e-2ae6-4928-8530-f9baf3ce7760
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 810,
          "y": 490
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      ids:
        simple: ${inputs.Device_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Searches for a device that matches the query.
      id: 515fe16c-e6ae-4d1d-81fe-ba0381cc1751
      iscommand: true
      name: Get device info
      script: '|||cs-falcon-search-device'
      type: regular
      version: -1
    taskid: 515fe16c-e6ae-4d1d-81fe-ba0381cc1751
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 990,
          "y": 690
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: CrowdStrike.Device.Status
          operator: isEqualString
          right:
            value:
              simple: normal
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c315fcda-4663-4738-86c4-bf95a872d727
      iscommand: false
      name: Is the device ready for isolation?
      type: condition
      version: -1
    taskid: c315fcda-4663-4738-86c4-bf95a872d727
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 990,
          "y": 890
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      ids:
        simple: ${inputs.Device_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Contains containment for a specified host. When contained, a host
        can only communicate with the CrowdStrike cloud and any IPs specified in your
        containment policy.
      id: fba9ba7d-fd1b-4f96-81a9-63dc3520a1b0
      iscommand: true
      name: Isolate endpoint
      script: '|||cs-falcon-contain-host'
      type: regular
      version: -1
    taskid: fba9ba7d-fd1b-4f96-81a9-63dc3520a1b0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 990,
          "y": 1230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_2_no": 0.85,
      "3_2_#default#": 0.2,
      "3_4_yes": 0.51,
      "5_2_#default#": 0.38,
      "5_6_yes": 0.72
    },
    "paper": {
      "dimensions": {
        "height": 1785,
        "width": 920,
        "x": 450,
        "y": 40
      }
    }
  }
