contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 406b8c87-ddbd-4a26-8a2f-8c161e9446ff
inputs: []
name: sharon
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0bdd4698-c527-4d2b-8634-6c60f54190a8
      iscommand: false
      name: ""
      version: -1
    taskid: 0bdd4698-c527-4d2b-8634-6c60f54190a8
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: the_field
              operator: notEndWith
              right:
                value:
                  simple: uuii
          root: the_field
          transformers:
          - operator: toUpperCase
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: bb213c79-077d-4ed7-83a6-750e5f90a089
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: bb213c79-077d-4ed7-83a6-750e5f90a089
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: the_other_field
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: f50c752f-df68-419d-8382-d5c4aeeb5db3
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: f50c752f-df68-419d-8382-d5c4aeeb5db3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 455,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
