contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 276489b7-be48-4927-8677-767693c486be
inputs: []
name: playbook_with_dep
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d4c45827-f85a-4abd-8562-761a457aff83
      iscommand: false
      name: ""
      version: -1
    taskid: d4c45827-f85a-4abd-8562-761a457aff83
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4c0e95c5-118c-450b-8541-217da71c96f6
      iscommand: false
      name: Untitled Task
      script: 602477fd-7ca8-4ede-8283-b3cb96fa1615
      type: regular
      version: -1
    taskid: 4c0e95c5-118c-450b-8541-217da71c96f6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 60,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8b3a79db-426a-46bb-87c8-7e4b34ef8704
      iscommand: false
      name: Untitled Task
      script: 602477fd-7ca8-4ede-8283-b3cb96fa1615
      type: regular
      version: -1
    taskid: 8b3a79db-426a-46bb-87c8-7e4b34ef8704
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 430
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 475,
        "width": 390,
        "x": 50,
        "y": 50
      }
    }
  }
