contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 11684f15-b9b9-4d20-8187-152a5d6a981d
inputs: []
name: zan_test_11
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4e32d988-b18e-46cb-8d4b-b3b2b0dd8553
      iscommand: false
      name: ""
      version: -1
    taskid: 4e32d988-b18e-46cb-8d4b-b3b2b0dd8553
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 720,
          "y": -130
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: I'm going to update zan's custom field"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: ab3edfbe-68ef-4e8e-8fa7-efc627d53962
      iscommand: false
      name: print
      script: Print
      type: regular
      version: -1
    taskid: ab3edfbe-68ef-4e8e-8fa7-efc627d53962
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 720,
          "y": 60
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8814974b-0b66-4f86-8a95-d0b97525644f
      iscommand: false
      name: run zan automation
      script: ed78755c-b02f-44c4-821c-d74614ac48d5
      type: regular
      version: -1
    taskid: 8814974b-0b66-4f86-8a95-d0b97525644f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 720,
          "y": 260
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 64439d1a-8b5e-4dc9-8fdc-67a056051b8a
      iscommand: false
      name: end
      type: title
      version: -1
    taskid: 64439d1a-8b5e-4dc9-8fdc-67a056051b8a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 720,
          "y": 450
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 645,
        "width": 380,
        "x": 720,
        "y": -130
      }
    }
  }
