contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: dec60c8a-04f0-4e91-8206-88dcd94ed5fe
inputs: []
name: Inner Loop
outputs:
- contextPath: Flag
  type: boolean
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c1bd32b5-6719-4502-8d7a-a8eb262de7f4
      iscommand: false
      name: ""
      version: -1
    taskid: c1bd32b5-6719-4502-8d7a-a8eb262de7f4
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    defaultassigneecomplex:
      simple: admin
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Start
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 2b318a2a-9d9c-44e9-80c6-63363d52acea
      iscommand: false
      name: Start
      script: Print
      type: regular
      version: -1
    taskid: 2b318a2a-9d9c-44e9-80c6-63363d52acea
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "2":
    continueonerrortype: ""
    defaultassigneecomplex:
      simple: admin
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: 'Counter is: ${counter}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 595a5baf-3199-4056-8815-e8c9a3fa6488
      iscommand: false
      name: Print counter
      script: Print
      type: regular
      version: -1
    taskid: 595a5baf-3199-4056-8815-e8c9a3fa6488
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 770
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: counter
      value:
        complex:
          root: counter
          transformers:
          - args:
              by:
                value:
                  simple: "1"
            operator: addition
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 8f0083e8-8d1f-4786-8e28-2085189b2811
      iscommand: false
      name: Increase counter
      script: Set
      type: regular
      version: -1
    taskid: 8f0083e8-8d1f-4786-8e28-2085189b2811
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 470
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 815,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
