contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.3.3
    packID: Flashpoint
    packName: Flashpoint
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: |-
  Compromised Credentials Match playbook uses the details of the compromised credentials ingested from the Flashpoint and authenticates using the Active Directory integration by providing the compromised credentials of the user, expires the credentials if it matches, and sends an email alert about the breach.
  Supported integrations:
  - Flashpoint
  - OpenLDAP
  - Active Directory Query v2
id: Compromised Credentials Match - Flashpoint
inputs:
- description: The username of the compromised credentials account.
  key: username
  playbookInputQuery: null
  required: true
  value:
    complex:
      accessor: flashpointcompromisedemail
      root: incident
- description: The password of the compromised credentials account.
  key: password
  playbookInputQuery: null
  required: true
  value:
    complex:
      accessor: flashpointcompromisedpassword
      root: incident
- description: Boolean input whether to send email or not.
  key: sendEmailAsWarning
  playbookInputQuery: null
  required: false
  value:
    simple: "True"
name: Compromised Credentials Match - Flashpoint
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bb3d91fc-387a-4329-8dbe-cf4f8a7830c0
      iscommand: false
      name: ""
      version: -1
    taskid: bb3d91fc-387a-4329-8dbe-cf4f8a7830c0
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 720,
          "y": -430
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      extend-context:
        simple: ad_output=.
      password:
        simple: ${inputs.password}
      username:
        complex:
          root: inputs.username
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Performs a simple bind operation on the LDAP server.
      id: 82f381e5-6edf-4274-87a1-34a8dc1c3c37
      iscommand: true
      name: Authenticate user
      script: '|||ad-authenticate'
      tags:
      - authenticate
      type: regular
      version: -1
    taskid: 82f381e5-6edf-4274-87a1-34a8dc1c3c37
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1130,
          "y": 390
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      username:
        complex:
          root: inputs.username
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Expires the password of an Active Directory user.
      id: 1e17db1a-f173-4247-8f71-e8f88f3381ca
      iscommand: true
      name: Expire current password
      script: '|||ad-expire-password'
      type: regular
      version: -1
    taskid: 1e17db1a-f173-4247-8f71-e8f88f3381ca
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1270,
          "y": 1080
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      body:
        simple: |-
          Hi,

          Your password at ${incident.flashpointaffecteddomain} has been breached and should be changed.

          Thanks
      subject:
        simple: Compromised Credential
      to:
        complex:
          root: inputs.username
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends an email.
      id: 02837f42-01ce-4432-8223-e150e7b43cbe
      iscommand: true
      name: Send password reset mail
      script: '|||send-mail'
      type: regular
      version: -1
    taskid: 02837f42-01ce-4432-8223-e150e7b43cbe
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 980,
          "y": 1580
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5d808528-08fc-4beb-8fe7-f7f0b61d3cb1
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 5d808528-08fc-4beb-8fe7-f7f0b61d3cb1
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 630,
          "y": 1840
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: OpenLDAP
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the OpenLDAP Integration is enabled or not.
      id: 19af1a48-500e-4467-840a-998ae2dd95dc
      iscommand: false
      name: Is OpenLDAP integration enabled?
      type: condition
      version: -1
    taskid: 19af1a48-500e-4467-840a-998ae2dd95dc
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 890,
          "y": -60
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: inputs.sendEmailAsWarning
                    operator: isEqualString
                    right:
                      value:
                        simple: "True"
                root: inputs.sendEmailAsWarning
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    defaultassigneecomplex:
      simple: Analyst
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "Yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether send email warning is enabled or not.
      id: 6aede180-305b-4a03-8678-d862ce7bcfdf
      iscommand: false
      name: Is send email as warning enabled?
      type: condition
      version: -1
    taskid: 6aede180-305b-4a03-8678-d862ce7bcfdf
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 870,
          "y": 1320
        }
      }
  "10":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Active Directory Query v2
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the Active Directory Query v2 Integration is enabled
        or not.
      id: 567756bf-92ae-4333-8570-c8456db6d757
      iscommand: false
      name: Is Active Directory Query V2 integration enabled?
      type: condition
      version: -1
    taskid: 567756bf-92ae-4333-8570-c8456db6d757
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1130,
          "y": 830
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: incident.type
                    operator: isEqualString
                    right:
                      value:
                        simple: Flashpoint Compromised Credentials
                root: incident.type
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Check whether the IncidentType is Flashpoint Compromised Credentials
        or not. '
      id: 274777c7-0d46-4d04-8939-c7e0f07d5681
      iscommand: false
      name: Is IncidentType Flashpoint Compromised Credentials?
      type: condition
      version: -1
    taskid: 274777c7-0d46-4d04-8939-c7e0f07d5681
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1130,
          "y": 160
        }
      }
  "13":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: ad_output
                    operator: isEqualString
                    right:
                      value:
                        simple: Done
                root: ad_output
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether authentication is successful or not.
      id: 93287df5-fe2f-4064-8baa-a9cecfb6f80f
      iscommand: false
      name: Is authentication successful?
      type: condition
      version: -1
    taskid: 93287df5-fe2f-4064-8baa-a9cecfb6f80f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1130,
          "y": 590
        }
      }
  "15":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Flashpoint
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the Flashpoint Integration is enabled or not.
      id: ec52760a-92d0-4460-8fdb-3effc462d3a7
      iscommand: false
      name: Is Flashpoint integration enabled?
      type: condition
      version: -1
    taskid: ec52760a-92d0-4460-8fdb-3effc462d3a7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 720,
          "y": -280
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "10_5_yes": 0.76,
      "10_9_#default#": 0.31,
      "15_7_#default#": 0.26,
      "8_9_#default#": 0.26
    },
    "paper": {
      "dimensions": {
        "height": 2335,
        "width": 1020,
        "x": 630,
        "y": -430
      }
    }
  }
