contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 52e79660-adf4-4262-8e3a-f7e3bc71ae48
inputs: []
name: test22_23_copy
outputs: []
sourceplaybookid: 81906b4b-bb11-4397-8a3a-268094e30b9b
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5ad3cf74-431e-4ca9-89c3-849a8482536e
      iscommand: false
      name: ""
      version: -1
    taskid: 5ad3cf74-431e-4ca9-89c3-849a8482536e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e0040d96-b189-41d1-8e43-c525fa05a286
      iscommand: false
      name: foo script
      script: c6146778-5598-4168-8d06-896c3c945ad8
      type: regular
      version: -1
    taskid: e0040d96-b189-41d1-8e43-c525fa05a286
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 980,
          "y": 350
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      arg1:
        simple: "23324"
      arg2:
        simple: ere
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        First create new instance of "HelloWorld Feed (Community Contribution)"
      id: d3e2ef1f-e053-4aee-8e5d-8f985817a3a2
      iscommand: false
      name: zan_script1
      script: 40f52bf9-bc24-42fe-8ccf-914336cde3b9
      type: regular
      version: -1
    taskid: d3e2ef1f-e053-4aee-8e5d-8f985817a3a2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 160,
          "y": 330
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "1"
      "yes":
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      left:
        simple: "12"
      right:
        simple: "12"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: c332cc30-81ba-4405-839f-b4d517b40c3a
      iscommand: false
      name: arevalue
      script: AreValuesEqual
      type: condition
      version: -1
    taskid: c332cc30-81ba-4405-839f-b4d517b40c3a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 160
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3bc70c08-8314-425b-8e19-dbb4d6a568c1
      iscommand: false
      name: Untitled Task
      type: title
      version: -1
    taskid: 3bc70c08-8314-425b-8e19-dbb4d6a568c1
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 890
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 905,
        "width": 1200,
        "x": 160,
        "y": 50
      }
    }
  }
