contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.2.12
    packID: ""
    packName: HelloWorld
    propagationLabels:
    - all
    toServerVersion: ""
description: This is a playbook which will handle the alerts coming from the Hello
  World service
id: 148a558b-c5a1-4e82-872a-e76fd9052b05
inputs:
- description: Alert ID to retrieve details for. By default retrieves from the HelloWorld
    ID custom field in the HelloWorld incident type
  key: AlertID
  playbookInputQuery: null
  required: false
  value:
    simple: ${incident.helloworldid}
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: ssdeep:*
    queryEntity: indicators
    results: null
    runFromLastJobTime: false
  required: false
  value: {}
name: Handle Hello World Alert_copy
outputs: []
quiet: true
sourceplaybookid: Handle Hello World Alert
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 37ea0ae7-8aa0-46e5-8e61-e5645bbe4b9a
      iscommand: false
      name: ""
      version: -1
    taskid: 37ea0ae7-8aa0-46e5-8e61-e5645bbe4b9a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: ssdeep:* and value:"199b9e9a7533431731fbb08ff19d437de1de6533f3ebbffc1e13eeffaa4fd455"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets a list of indicator objects and the associated indicator outputs
        that match the specified query and filters. The results are returned in a
        structured data file.
      id: 0b2b8997-e31e-4f8a-8e1a-7b2ff1212c07
      iscommand: false
      name: Get Indicator with ssdeep
      script: GetIndicatorsByQuery
      type: regular
      version: -1
    taskid: 0b2b8997-e31e-4f8a-8e1a-7b2ff1212c07
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: d17ac004-cde2-46cb-85dc-32dc69e81538
      iscommand: false
      name: DBot Indicator Enrichment - Generic
      playbookId: dbot_indicator_enrichment_-_generic
      type: playbook
      version: -1
    taskid: d17ac004-cde2-46cb-85dc-32dc69e81538
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -150,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3d8b7ea9-bd8d-42f2-8e1d-768b133ddc7d
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 3d8b7ea9-bd8d-42f2-8e1d-768b133ddc7d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 70,
          "y": 600
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 2
    scriptarguments:
      ssdeep_hash:
        simple: ${File.SSDeep}
      ssdeep_hashes_to_compare:
        simple: ${playbookQuery.CustomFields.ssdeep}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This script finds similar files that can be related to each other
        by fuzzy hash (SSDeep).
      id: b55dac30-b297-407e-8cf0-e3287a0ea594
      iscommand: false
      name: check SSDSimilarity
      script: SSDeepSimilarity
      type: regular
      version: -1
    taskid: b55dac30-b297-407e-8cf0-e3287a0ea594
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 330,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 615,
        "width": 860,
        "x": -150,
        "y": 50
      }
    }
  }
