contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: dc1f1c4c-901f-47a4-85ab-8c9ea368fdb6
inputs: []
name: zan_plybook_loop_regression_6.9
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cba7ef91-0e4a-4705-8dcd-09d1139e9a24
      iscommand: false
      name: ""
      version: -1
    taskid: cba7ef91-0e4a-4705-8dcd-09d1139e9a24
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      execution-timeout:
        simple: "108000"
      seconds:
        simple: "108000"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: 550db97b-8a11-429b-8ef6-deda9af245ac
      iscommand: false
      name: Sleep
      script: Sleep
      type: regular
      version: -1
    taskid: 550db97b-8a11-429b-8ef6-deda9af245ac
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 360
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Starting
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: b7f7b89a-47f4-4bfa-8bde-c016829d5683
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: b7f7b89a-47f4-4bfa-8bde-c016829d5683
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 180
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Ending
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 561b8a2d-c5a4-4b30-865c-cad12321b683
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 561b8a2d-c5a4-4b30-865c-cad12321b683
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 540
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 585,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
