contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 4507afae-5d3a-4eb6-8cd2-ed4f8bcebdd7
inputs: []
name: zan_child
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b4feca2f-a9d5-4409-8476-95fb0a08311d
      iscommand: false
      name: ""
      version: -1
    taskid: b4feca2f-a9d5-4409-8476-95fb0a08311d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: zan
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: eebb956d-e3e7-4fc5-8358-9dedc3f77b8f
      iscommand: false
      name: Untitled Task
      script: Print
      type: regular
      version: -1
    taskid: eebb956d-e3e7-4fc5-8358-9dedc3f77b8f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 320
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f2fd4253-d06d-4990-8b7e-64c2b6b2a918
      iscommand: false
      name: Untitled Task
      type: title
      version: -1
    taskid: f2fd4253-d06d-4990-8b7e-64c2b6b2a918
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 520
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 535,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
